from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from jinja2 import Environment, FileSystemLoader, StrictUndefined

ProjectKind = Literal["bundle-job", "bundle-pipeline", "bundle-sql", "bundle-dashboard"]

DEFAULT_DEPLOYMENT_STRATEGY = "external-deployer"
DEFAULT_TARGET = "dev"


class ProjectCreateError(ValueError):
    pass


@dataclass(frozen=True)
class TemplateSpec:
    template: str
    destination: str
    include_github_action: bool = False


TEMPLATE_SPECS: dict[ProjectKind, list[TemplateSpec]] = {
    "bundle-job": [
        TemplateSpec("databricks.yml.j2", "databricks.yml"),
        TemplateSpec("resources/job.yml.j2", "resources/job.yml"),
        TemplateSpec("src/jobs/main.py.j2", "src/jobs/main.py"),
        TemplateSpec("tests/test_placeholder.py.j2", "tests/test_placeholder.py"),
        TemplateSpec("README.md.j2", "README.md"),
        TemplateSpec("gitignore.j2", ".gitignore"),
        TemplateSpec(".github/workflows/bundle-validate.yml.j2", ".github/workflows/bundle-validate.yml", True),
    ],
    "bundle-pipeline": [
        TemplateSpec("databricks.yml.j2", "databricks.yml"),
        TemplateSpec("resources/pipeline.yml.j2", "resources/pipeline.yml"),
        TemplateSpec("src/pipelines/pipeline.py.j2", "src/pipelines/pipeline.py"),
        TemplateSpec("tests/test_placeholder.py.j2", "tests/test_placeholder.py"),
        TemplateSpec("README.md.j2", "README.md"),
        TemplateSpec(".github/workflows/bundle-validate.yml.j2", ".github/workflows/bundle-validate.yml", True),
    ],
    "bundle-sql": [
        TemplateSpec("databricks.yml.j2", "databricks.yml"),
        TemplateSpec("resources/sql.yml.j2", "resources/sql.yml"),
        TemplateSpec("sql/001_create_tables.sql.j2", "sql/001_create_tables.sql"),
        TemplateSpec("tests/test_placeholder.py.j2", "tests/test_placeholder.py"),
        TemplateSpec("README.md.j2", "README.md"),
        TemplateSpec(".github/workflows/bundle-validate.yml.j2", ".github/workflows/bundle-validate.yml", True),
    ],
    "bundle-dashboard": [
        TemplateSpec("databricks.yml.j2", "databricks.yml"),
        TemplateSpec("resources/dashboard.yml.j2", "resources/dashboard.yml"),
        TemplateSpec("dashboards/README.md.j2", "dashboards/README.md"),
        TemplateSpec("README.md.j2", "README.md"),
        TemplateSpec(".github/workflows/bundle-validate.yml.j2", ".github/workflows/bundle-validate.yml", True),
    ],
}

TEMPLATE_DIRS: dict[ProjectKind, str] = {
    "bundle-job": "databricks_bundle_job",
    "bundle-pipeline": "databricks_bundle_pipeline",
    "bundle-sql": "databricks_bundle_sql",
    "bundle-dashboard": "databricks_bundle_dashboard",
}


def create_project(
    *,
    kind: ProjectKind,
    name: str,
    output_dir: Path | None = None,
    force: bool = False,
    include_github_action: bool = False,
    deployment_strategy: str = DEFAULT_DEPLOYMENT_STRATEGY,
    target: str = DEFAULT_TARGET,
    dry_run: bool = False,
) -> dict[str, object]:
    if kind not in TEMPLATE_SPECS:
        raise ProjectCreateError(f"Unsupported project kind: {kind}")
    if not name or "/" in name or "\\" in name:
        raise ProjectCreateError("Project name must be a non-empty folder name.")
    if target != DEFAULT_TARGET:
        raise ProjectCreateError("Only the dev target is generated by this workflow.")

    destination_root = ((output_dir or Path.cwd()) / name).resolve()
    context = {
        "name": name,
        "bundle_name": _normalize_identifier(name),
        "deployment_strategy": deployment_strategy,
        "target": target,
    }
    rendered_files = _render_project(kind, context, include_github_action=include_github_action)
    conflicts = [str(path) for path in rendered_files if (destination_root / path).exists()]

    if conflicts and not force:
        return {
            "kind": kind,
            "name": name,
            "root_path": str(destination_root),
            "dry_run": dry_run,
            "created": False,
            "files": [str(path) for path in rendered_files],
            "conflicts": conflicts,
        }

    if not dry_run:
        for relative_path, content in rendered_files.items():
            target_path = destination_root / relative_path
            target_path.parent.mkdir(parents=True, exist_ok=True)
            target_path.write_text(content, encoding="utf-8")

    return {
        "kind": kind,
        "name": name,
        "root_path": str(destination_root),
        "dry_run": dry_run,
        "created": not dry_run,
        "files": [str(path) for path in rendered_files],
        "conflicts": conflicts,
    }


def _render_project(
    kind: ProjectKind,
    context: dict[str, str],
    *,
    include_github_action: bool,
) -> dict[Path, str]:
    template_root = _templates_root() / TEMPLATE_DIRS[kind]
    env = Environment(
        loader=FileSystemLoader(template_root),
        autoescape=False,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
    )
    return {
        Path(spec.destination): env.get_template(spec.template).render(**context)
        for spec in TEMPLATE_SPECS[kind]
        if include_github_action or not spec.include_github_action
    }


def _templates_root() -> Path:
    return Path(__file__).resolve().parents[4] / "templates"


def _normalize_identifier(value: str) -> str:
    normalized = "".join(char if char.isalnum() else "_" for char in value.lower()).strip("_")
    return normalized or "databricks_bundle"
